from .battle import BattleForm
from .forms import (
    AdvisorForm,
    AllianceForm,
    AnnounceForm,
    AttackForm,
    BankTransferForm,
    CallForm,
    ClaimForm,
    ContractForm,
    DebtPayForm,
    DeploymentForm,
    FacilityForm,
    GodForm,
    GovernanceForm,
    InvestForm,
    JointFacilityForm,
    LetterForm,
    LawForm,
    MaintenanceForm,
    MailForm,
    MeetingForm,
    MilitaryFactoryForm,
    MilitarySaleForm,
    SaleForm,
    SanctionForm,
    SpeechForm,
    TariffForm,
)
from .military_base import MilitaryBaseForm
from .satellite import SatelliteForm

__all__ = [
    "AdvisorForm",
    "AllianceForm",
    "AnnounceForm",
    "AttackForm",
    "BankTransferForm",
    "BattleForm",
    "CallForm",
    "ClaimForm",
    "ContractForm",
    "DebtPayForm",
    "DeploymentForm",
    "FacilityForm",
    "GodForm",
    "GovernanceForm",
    "InvestForm",
    "JointFacilityForm",
    "LetterForm",
    "LawForm",
    "MaintenanceForm",
    "MailForm",
    "MeetingForm",
    "MilitaryBaseForm",
    "MilitaryFactoryForm",
    "MilitarySaleForm",
    "SaleForm",
    "SanctionForm",
    "SatelliteForm",
    "SpeechForm",
    "TariffForm",
]
